### PR TITLE
[Bug] fix to apply reward spread by multiplication

### LINKED ISSUE #280: [BUG] oracle reward band is too tight
**Describe the bug**
At oracle tally, the reward band is ratio but it is applied by addition operation. Due to this bug, it just allow 0.1 exchange rate error.

**To Reproduce**
Do oracle vote with different exchange-rates more than 0.1.

**Context & versions**
v0.3.0-rc1

**(if applicable) suggested solution**
Change addition operation to multiplication

### PR DESCRIPTION
**Pull request by YunSuk-Yeo**
## Summary of changes

* Apply oracle reward spread with multiplication operation

close #280 

## Report of required housekeeping

- [x] Github issue OR spec proposal link
- [x] Wrote tests
- [ ] Updated relevant documentation (docs/)
- [ ] Added a relevant changelog entry: clog add [section] [stanza] [message]

----

## (FOR ADMIN) Before merging

- [ ] Added appropriate labels to PR
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" (coding standards)
- [ ] Confirm added tests are consistent with the intended behavior of changes
- [ ] Ensure all tests pass

### CODE REVIEW

File: x/oracle/tally.go [hunk 1]
```diff
@@ -16,12 +17,14 @@ func tally(ctx sdk.Context, pb types.ExchangeRateBallot, rewardBand sdk.Dec) (we
...
 	weightedMedian = pb.WeightedMedian()
 	standardDeviation := pb.StandardDeviation()
-	rewardSpread := rewardBand.QuoInt64(2)
+	rewardSpread := weightedMedian.Mul(rewardBand.QuoInt64(2))
 
 	if standardDeviation.GT(rewardSpread) {
 		rewardSpread = standardDeviation
 	}
 
+	fmt.Println(standardDeviation)
```
Comment (hanjukim) [inline x/oracle/tally.go]: remove println

Comment (YunSuk-Yeo) [reply x/oracle/tally.go]: Thanks done!
